_extends: github-settings

from_owner: 
  - dependabot[bot]

required_labels: 
  - dependencies

blacklisted_labels:
  - wip

apply_labels:
  - merge

webhook_url: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX

slack_user_mapping:
  githubUsername1: "slackUserID1"
  githubUsername2: "slackUserID2"
